created entity and stored into core data using Magical Record pod
samsonsunny/swiftDemoApp pull request #1
Opened 2017-01-30 13:35 UTC by samsonsunny

2017-01-30 13:51 UTC, ramesh-lingappan requested changes

2017-01-30 13:51 UTC, ramesh-dev commented on LoginApp/LoginViewController.swift
> +			if !response.0 {
use proper naming for tuples, here 0 and 1 represents nothing, until we dig further inside.

2017-01-30 13:51 UTC, ramesh-dev commented on LoginApp/LoginViewController.swift
> +			if let user: UserInfo = UserInfo.mr_findFirst(byAttribute: "emailId", withValue: email) as? UserInfo
No Password check?

2017-01-31 13:26 UTC, samsonsunny commented on LoginApp/LoginViewController.swift
> +			if !response.0 {
Sure I ll use proper naming convention even it is simple logic.

2017-01-31 13:26 UTC, samsonsunny commented on LoginApp/LoginViewController.swift
> +			if let user: UserInfo = UserInfo.mr_findFirst(byAttribute: "emailId", withValue: email) as? UserInfo
I forgot to check that. I ll add that too.

2017-02-01 06:07 UTC, gupta515 commented on LoginApp/ChangePasswordViewController.swift
> +		let emailId = defaults.object(forKey: "loggedInUserEmail") as? String
This line, fetching user mailId from user defaults can be in guard statement.

2017-02-01 06:08 UTC, gupta515 commented on LoginApp/ChangePasswordViewController.swift
> +			showAlert(message: "Please provide old password")
Alert should be "Please provide correct old password"

2017-02-01 06:53 UTC, merged